version: '2'
services:
    cards-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/cards/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=cards
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
